---
- name: Add Puppet Labs GPG key.
  rpm_key:
    key: https://yum.puppet.com/RPM-GPG-KEY-puppet
    state: present

- name: Add Puppet Labs repositories.
  package: name={{ puppet_yum_rpm }} state=present
